name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
