name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: lukka/get-cmake@latest
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: run-cmake
      uses: lukka/run-cmake@v10.8
      with:
        configurePreset: Release
        buildPreset: Release

              
