name: Build
on:
  push:
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
    - name: Configure project in debug
      run: cmake --preset Debug
           cmake --build build  
           cmake --preset Release
           cmake --build build         
